#!/usr/bin/bash
all=`ls  ./DataBase`
echo $all
concate=","
final=""
counter=0
echo "Enter DataBase Name "
read dbname
search=`ls ./DataBase/$dbname |grep .txt | awk -F.  '
{
print $1;
} '`
if [[ $USER == $search  ]]
then

echo "Enter Table Name! "
read name

header=`cat  ./DataBase/$dbname/$name | head -1 `
echo $header
no_col=`cat  test.table|head -1| awk -F "," '{print NF-1}'`
echo $no_col
echo "Insert Into Table "
for((i =1 ;i<= no_col ;i++ ))
do
read colname
final+="${colname}${concate}"

done
echo $final
echo $final >> ./DataBase/$dbname/$name

fi
